### ISSUE TITLE
Explain buffer attribute

### ISSUE THREAD

**Issue by henrahmagix** [Venturocket/angular-slider#16]
I found it in your example page but it's not explained in the README. In code, a comment says:

> how close can the two knobs of a dual knob slider get?

**Comment by henrahmagix** [comment]
I can see it's explained in the [GitHub Pages site](http://venturocket.github.io/angular-slider/), which I think is out of date (see #17)

**Comment by drgould** [comment]
I just pushed out v0.3.0 and updated the README and ghpages site to include an explanation of the buffer attribute. Happy sliding.
