### ISSUE TITLE
ng-change doesn't fire

### ISSUE THREAD

**Issue by juniorplenty** [Venturocket/angular-slider#19]
Using this code (`less` syntax):

```
slider(
  floor="0"
  ceiling="{{ placement.contracted_delivery }}"
  ng-model="flight.target"
  step="1"
  stretch="1"
  ng-change="allocate(flight)")
```

...the ng-change function never fires, it seems like it get sucked up by the directive.

**Comment by drgould** [comment]
There's might be a couple reasons for this:
1. isolate scoping used by the slider
2. non-standard use of ng-model by the slider

I'll take a look at this over the weekend.

**Comment by bertop89** [comment]
Found same issue the other day, tried to use a watch over the ng-model but was too slow.

**Comment by drgould** [comment]
`ngChange` support has been added in v0.3.0. Happy sliding!
