### ISSUE TITLE
support for ng-transclude

### ISSUE THREAD

**Issue by follavi** [Venturocket/angular-slider#2]
The code doesn't work into a ng-transclude scope. The issue was partially solved for a previous version in https://github.com/brianmcd/angular-slider. Is it possible to change the code accordingly to resolve this issue ?

Thanks in advance

**Comment by drgould** [comment]
Yeah, we'll figure something out.

**Comment by drgould** [comment]
I pushed up v0.2.0 which includes the fix for this.

**Comment by follavi** [comment]
Thank you, it will be very useful !

Have a nice day,

Thomas
