### ISSUE TITLE
Slider doesn't set form to a dirty state

### ISSUE THREAD

**Issue by perry** [Venturocket/angular-slider#21]
The pristine state on a `<form>` is only changed when the model is directly changed by the `<input>`.

We could potentially pass the form object and a field name (this would also require you adding a hidden `<input>` field with a `name` attribute to register it in the form) in to the slider and do something like `scope.myForm.myField.$setViewValue(scope.myForm.myField.$viewValue);` when the `ngModel` changes - this would handle all of the state changes that a form could have.

Any ideas on a better way to do this?

**Comment by drgould** [comment]
Seems a bit unnecessary requiring the form to be passed in. I'll see what I can come up with.

**Comment by drgould** [comment]
`ngModelController` has been implemented in v0.3.0 and the slider sets its state to dirty upon user interaction. Happy sliding!

**Comment by henrahmagix** [comment]
Thanks @drgould!

**Comment by perry** [comment]
Thanks! :beers:
