### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by jasadams** [Venturocket/angular-slider#26]
Ah, I just installed via bower and there are no js files in the build directory. When I manually download and put the files there and start to use it. I just get some overlapping text where the slider should be. Where's the CSS?

**Comment by henrahmagix** [comment]
@perry commented to explain just that: https://github.com/Venturocket/angular-slider/commit/03dbdbbf9d47cdc05f4e37effd23235b41700d74#commitcomment-6026853

**Comment by drgould** [comment]
Damn, sorry. I just fixed this in v0.3.1
