### ISSUE TITLE
Exponential slider

### ISSUE THREAD

**Issue by CMCDragonkai** [Venturocket/angular-slider#3]
I need the slider to start to slowly increase values such as 1 - 10 in +1 increments, but from then on wards, it increases from 10 to 10,000 by +10 increments, and then so on.

What would be the best way to implement this in angular-slider?

**Comment by drgould** [comment]
I don't know of any quick hack solution, but I'll definitely bake this in.

**Comment by CMCDragonkai** [comment]
Awesome thanks.

**Comment by drgould** [comment]
I just pushed up v0.2.0 with this capability.
