### ISSUE TITLE
Full touch event support

### ISSUE THREAD

**Issue by torleifhalseth** [Venturocket/angular-slider#32]
What happend to the touch support?

Tested on an iPad without any luck.

**Comment by torleifhalseth** [comment]
Fixed by using bower versions of all dependecies. Don't know why it worked, but it does.

**Comment by mohdmasd** [comment]
Can you please explain what you did? I'm having the same issue with touch support.

**Comment by ben-sykes** [comment]
Were you able to figure out exactly what solved the touch support issue?
