### ISSUE TITLE
Incorrect behavior when slider shown using ng-show

### ISSUE THREAD

**Issue by cwhite92** [Venturocket/angular-slider#37]
Hi!

I'm trying to use the slider on one of my Angular pages and it doesn't seem to be behaving when it's hidden using `ng-show`.

This is basically the markup I'm using:

```
<div ng-show="someCondition">
    <slider ng-model="test" floor="-10" ceiling="10" step="5"></slider>
</div>
```

I can see the slider directive is running code when you first load the page (as directives do), and I think it's incorrectly determining the widths and offsets of its elements because the element is hidden when the slider initializes. It ends up looking something like this: http://i.imgur.com/jJrY8N4.png

Then, after it's clicked, it seems to reset itself back to normal: http://i.imgur.com/cgRxeMB.png

Is there any way to "recalculate" its widths and offsets when the element with the `slider` directive is shown?

It's a shame this problem exists, this is the best slider I've found for Angular. :(

**Comment by joscha** [comment]
did you try `$scope.$broadcast('refreshSlider');` after show?

**Comment by radiophysicist** [comment]
Trick suggested by joscha with `$scope.$broadcast('refreshSlider')` worked successfully for me

**Comment by drgould** [comment]
I'm in the process of completely rewriting the slider. I'll make sure I take this into account.

**Comment by wender** [comment]
We had same behaviour here, we solved using broadcast to refreshSlider, but we have in the same page a ng-autocomplete which stopped working... i've solved by commenting the $timeout from your source

// listen for a refresh event
                            scope.$on('refreshSlider', function() {
                                // update the DOM, but make sure everything has been digested first
                                //$timeout(function() {
                                    updateDOM();
                                //});
                            });

Now, my slider is working and ng-autocomplete as well
