### ISSUE TITLE
slider touch not working

### ISSUE THREAD

**Issue by davemerwin** [Venturocket/angular-slider#6]
I'm not sure if I'm missing something, but the slider isn't working with touch

**Comment by drgould** [comment]
Which OS and browser are you using?

I've tested it in IE10/11 on Win 8/8.1, Chrome on Android, and Safari and Chrome on iOS; and they all work.

**Comment by davemerwin** [comment]
I'm testing it on iOS 7, chrome and safari. Any suggestions on debugging?

On Friday, February 21, 2014, Derek Gould notifications@github.com wrote:

> Which OS and browser are you using?
> 
> I've tested it in IE10/11 on Win 8/8.1, Chrome on Android, and Safari and
> Chrome on iOS; and they all work.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Venturocket/angular-slider/issues/6#issuecomment-35767275
> .

## 

Dave Merwin

http://facebook.com/davemerwin
http://twitter.com/davemerwin
http://www.davemerwin.com
My Profile: http://www.linkedin.com/in/merwin
541.335.1832

**Comment by drgould** [comment]
If you have a mac you can follow this: http://stackoverflow.com/questions/6206568/how-can-i-inspect-the-window-object-for-mobile-safari/12762449#12762449

**Comment by davemerwin** [comment]
Found the issue. There is a conflict for touch when jQuery is included in the build. I removed jQuery and that fixed it.

**Comment by drgould** [comment]
Interesting. Which version of jQuery?
