### ISSUE TITLE
The specified value ':)' does not conform to the required format, 'yyyy-MM-dd'.

### ISSUE THREAD

**Issue by goldins** [Venturocket/angular-slider#60]
I get these errors in the latest version of Google Chrome Canary (Version 39.0.2127.0 canary (64-bit))
`The specified value ':)' does not conform to the required format, 'yyyy-MM-dd'.`

`angular-slider.js:131`
`angular-slider.js:136`

A similar bug report has been filed with Modernizr in February 2012: https://github.com/Modernizr/Modernizr/issues/483 (Sorry if this bug should be filed with Modernizr too)

This was not an issue in previous versions of Canary.

**Comment by drgould** [comment]
I'm in the process of rewriting the slider from scratch without the need for Modernizr or any other kind of feature detection.
