### ISSUE TITLE
Strange dragging behavior

### ISSUE THREAD

**Issue by sclausen** [Venturocket/angular-slider#63]
If you drag with the mouse faster than the knob follows your cursor and you leave the knob, dragging stops.
If you then release your mouse button and return to the knob you drag again. Sometimes the left knob doesn't start to move if you click hold the button and move the mouse.

Here is my reproduction: http://plnkr.co/edit/Cm7r0gQk1xYmVQzlhB98?p=preview

**Comment by hstengard** [comment]
I have a similar behaviour but with a single knob.

When you start to drag and the cursor leaves the slider element the dragging stops. But when you return to the slider the knob starts to move again without any click.

I may be used to the jQuery slider where the dragging continues as long as you hold the mouse button anywhere on the screen. But I find the above behaviour a little strange. 

In my opinion the behaviour should be one of those. 
- Work as jQuery
- or stop when you leave the slider while dragging and make you click the knob again to start to drag. 

Thanks for a great job with this directive!

**Comment by dasblitz** [comment]
This is an issue with $swipe in ngTouch. A pull request for a fix can be found here: https://github.com/angular/angular.js/pull/8256/files
