### ISSUE TITLE
translate-fn firing multiple times

### ISSUE THREAD

**Issue by shahzainb** [Venturocket/angular-slider#67]
I have an issue with the translate-fn firing multiple times, even when not actually moving the slider. It fires during initialization and when showing/hiding, etc. The values each time are different as well, and not reflective of the value of the slider.

Example: http://jsfiddle.net/drzxbx9f/ (the slider won't show because there's no css, but you can look at the console log output to see what i mean)

**Comment by drgould** [comment]
The purpose of translate-fn is to modify the values displayed, so it has to fire for every knob/bubble which is visible (3 for a single knob slider, 6 for dual knob) whenever the slider is resized (initialization and show/hide are essentially resize events). As such, the fiddle you linked is working as expected.
