### ISSUE TITLE
Get Current Value?

### ISSUE THREAD

**Issue by queejie** [Venturocket/angular-slider#68]
Forgive me if this is a naive question. I'm a long-time developer, but just learning AngularJS.  

I have the ng-change working, but I can't figure out how to pass in or otherwise get the current slider value.  I'm also not sure how to reference the slider spans, as I would in jQuery.  I need to have other things on the page and the style of the pointer react to the current value of the slider.  The sliders are created in an ng-repeat loop, so I'm not sure what they're id attributes would be.

Thanks for any help you can provide, and thanks for the plugin.  

-- I figured out how to pass in the object, which contains the slider value.  I've also figured out what seems like a roundabout way to get to the jQuery version of the slider panes.  I pass 'this' in as and argument to the ng-change method, and it has a $index value set, so I know to use the nth slider object on the page.  Pretty sure this is not the optimal way to get the object.

**Comment by fobin** [comment]
example like this:

```
  <slider ng-model="sliderValue" floor="{{sliderMin}}" ceiling="{{sliderMax}}" step="{{sliderStep}}" ng-change="sliderAnswerThis()"></slider>
```

And then your scope automatically updates so you can use $scope.sliderValue in your change method. So based on the example this would console.log when ever the slider value changes:

```
$scope.sliderAnswerThis = function() {
  console.log($scope.sliderValue);
}
```

**Comment by queejie** [comment]
Thank you!
