### ISSUE TITLE
Clicking on left pointer is triggering the right pointer

### ISSUE THREAD

**Issue by jtomaszewski** [Venturocket/angular-slider#8]
My situation:
I have a slider with two knobs (pointers).

It's working great (thanks for the gem!), but: **clicking on the left pointer begins in fact clicks on right pointer and starts to move the range as I wanted to change the right's end of range**. Thus, moving the minimum limit of the range is really difficult for the user.

Let's look at the screen:
![image](https://f.cloud.github.com/assets/1862580/2264877/9a5db47a-9e78-11e3-9bc0-4531c210088b.png)

When I looked into source:
`.input.high` has the width as the yellow rectangle on the picture, but should be of width of the green square. 

`.input.high` and `.input.low` offsets should be `-= $('.pointer').width()`

I wanted to changed it but unfortunately source code currently is hardly readable right now (seems like it's translated from coffescript and there are no .coffee files here).

Meanwhile, if someone'd have the same issue, here's quick fix:

``` css
slider .input.high {
  margin-left: 20px; // if your span.pointer has 20px width
}
```

**Comment by drgould** [comment]
Yeah, I noticed this too while refactoring and reworking the code. I've fixed the issue but I'm waiting to push it up until I've finished a few other fixes and enhancements.
