### ISSUE TITLE
Touch Doesn't work with jQuery

### ISSUE THREAD

**Issue by James-Dunn** [Venturocket/angular-slider#9]
If I include jQuery, the touchmove events don't work on mobile browsers. http://jsbin.com/tukomono/1/edit

**Comment by drgould** [comment]
To be clear, I'm not maintaining prajwalkman's slider (the one used by the jsbin you linked). Yes I originally used his as the base for ours, but while they are similar in function, at this point there is basically no similarity in code. I've spent countless hours refining, enhancing and extending it to fit the variety of uses for which we and anyone else might need it. With that said, in my testing I haven't encountered any issues using jQuery alongside our slider on mobile browsers (we use it on http://venturocket.com with no reported issues for quite some time). Admittedly I haven't personally tested it on iOS for a while, but last time I did (maybe a month or two ago) it was working as expected.
